export const postsConstants = {
  REQUEST_POSTS         : 'REQUEST_POSTS',
  RECEIVE_POSTS         : 'RECEIVE_POSTS',
  FETCH_POSTS_ERROR     : 'FETCH_POSTS_ERROR',
  RESET_ERROR           : 'RESET_ERROR',
  LOAD_MORE_POSTS       : 'LOAD_MORE_POSTS',
  SEARCH_FROM_POST      : 'SEARCH_FROM_POST'
}